export {default as Header} from './Header/Header'
export {default as Main} from './Main/Main'
export {default as Footer} from './Footer/Footer'
export {default as InputText} from './Form/InputText'
export {default as FormButton} from './Form/FormButton'
export {default as SideCart} from './Cart/SideCart'